# Generated by Django 2.1 on 2018-08-24 16:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='pin',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200)),
        ),
    ]
