# Generated by Django 2.1 on 2018-08-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180824_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=50)),
                ('true_balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('account_type', models.CharField(choices=[('cheque', 'cheque'), ('credit', 'credit')], max_length=50)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Credential')),
            ],
        ),
    ]
