# Generated by Django 2.1 on 2018-08-26 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180825_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='month_to',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
