# Generated by Django 2.1 on 2018-08-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180826_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
