# Generated by Django 2.1 on 2019-02-08 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180924_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
