# Generated by Django 2.1 on 2019-03-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190318_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('cheque', 'cheque'), ('credit', 'credit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='credential',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Credential'),
        ),
    ]
