# Generated by Django 2.1 on 2021-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190324_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_group',
            field=models.CharField(blank=True, choices=[('transactional', 'transactional'), ('saving', 'saving')], max_length=50),
        ),
    ]
