# Generated by Django 2.1 on 2021-07-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210727_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='increase_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
