# Generated by Django 2.1 on 2021-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_transaction_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='has_interest_below_zero',
            field=models.BooleanField(default=False),
        ),
    ]
